graph TB
    subgraph docker["Docker Compose"]
        subgraph public["Public network"]
            proxy["Nginx reverse proxy"]
            webapp[".NET MVC Webapp Container"]
        end
        subgraph bridge["(public + internal)"]
            api[".NET API Container"]
        end
        subgraph internal["Internal network"]
            mongodb[("MongoDB Container")]
        end 
    end

    subgraph external_services["External Services"]
        cloudinary["Cloudinary image Storage"]
        mailservice["Mail Service"]
    end
    
    client["Client"]
    mobile_app["Flutter App"]
    
    client -->|HTTP| proxy 
    client --> mobile_app
    mobile_app -->|HTTP/REST| proxy
    proxy -->|/| webapp
    proxy -->|/api| api
    webapp -->|HTTP/REST| proxy
    api -->|Query/Update| mongodb
    api -->|Upload/Delete Images| cloudinary
    api -->|SMTP / HTTP API| mailservice

    style webapp fill:#4A90E2,color:#fff
    style api fill:#4A90E2,color:#fff
    style mongodb fill:#555555,color:#fff
    style docker fill:#f9f9f9,stroke:#333
    style client fill:#90EE90
    style mobile_app fill:#b1ecff
    style proxy fill:#3d9153,color:#fff
    style cloudinary fill:#F5A623,color:#000
    style mailservice fill:#F5A623,color:#000
    style external_services fill:#fff8ee,stroke:#F5A623
