graph TB
    
    subgraph public["Public Zone"]
        proxy["Nginx Reverse Proxy"]
        webapp["Webapp Server"]
    end
    subgraph backend["Backend Zone"]
        api["API Server"]
    end
    subgraph internal["Internal Zone"]
        mongodb[("MongoDB")]
    end
    

    external["Client"]
    mobile_app["Flutter App"]

    external -->|HTTP| proxy
    external --> mobile_app
    mobile_app -->|HTTP/REST| proxy
    proxy -->|/| webapp
    proxy -->|/api| api
    webapp -->|HTTP/REST| proxy
    api -->|Query/Update| mongodb

    style webapp fill:#4A90E2
    style api fill:#4A90E2
    style mongodb fill:#555555,color:#fff
    style external fill:#90EE90
    style mobile_app fill:#b1ecff
    style proxy fill:#3d9153